### ISSUE TITLE
Decoration fails for classes with constructor parameters

### ISSUE THREAD

**Issue by gbirke** [JeroenDeDauw/GenericDecorator#1]
Example code:

```php
class Foo {
    public function __construct( string $bar ) {
        $this->bar = $bar;
    }
}

$newFoo = new Foo( 'all work and no play makes Jack a dull boy' );

$decoratedFoo = ( new GenericDecorator\DecoratorBuilder( $newFoo ) )
           ->withBefore( function () {
               echo "Before function\n";
           } )
           ->withAfter( function () {
               $callingFunctionName = debug_backtrace()[7]['function'];
               echo "After function\n";
           } )
           ->newDecorator();
```

This code leads to the following output:

```
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Foo::__construct() must be of the type string, none given, called in /Users/gabi/tmp/proxy/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Generator.php on line 293 and defined in /Users/gabi/tmp/proxy/test.php:10
Stack trace:
#0 /Users/gabi/tmp/proxy/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Generator.php(293): Foo->__construct()
#1 /Users/gabi/tmp/proxy/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Generator.php(263): PHPUnit_Framework_MockObject_Generator->getObject('class Mock_Foo_...', 'Mock_Foo_076660...', 'Foo', true, true, Array, false, NULL)
#2 /Users/gabi/tmp/proxy/vendor/jeroen/generic-decorator/src/DecoratorBuilder.php(57): PHPUnit_Framework_MockObject_Generator->getMock('Foo', Array)
#3 /Users/gabi/tmp/proxy/vendor/jeroen/generic-decorator/src/DecoratorBuilder.php(44): GenericDecorator\DecoratorBuilder->newMock('Foo', Array)
#4 /Users/gabi/tmp/proxy/test.php(26): GenericDecorator\DecoratorBuilder->newDecorator in /Users/gabi/tmp/proxy/test.php on line 10

Fatal error: Uncaught TypeError: Argument 1 passed to Foo::__construct() must be of the type string, none given, called in /Users/gabi/tmp/proxy/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Generator.php on line 293 and defined in /Users/gabi/tmp/proxy/test.php:10
Stack trace:
#0 /Users/gabi/tmp/proxy/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Generator.php(293): Foo->__construct()
#1 /Users/gabi/tmp/proxy/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Generator.php(263): PHPUnit_Framework_MockObject_Generator->getObject('class Mock_Foo_...', 'Mock_Foo_076660...', 'Foo', true, true, Array, false, NULL)
#2 /Users/gabi/tmp/proxy/vendor/jeroen/generic-decorator/src/DecoratorBuilder.php(57): PHPUnit_Framework_MockObject_Generator->getMock('Foo', Array)
#3 /Users/gabi/tmp/proxy/vendor/jeroen/generic-decorator/src/DecoratorBuilder.php(44): GenericDecorator\DecoratorBuilder->newMock('Foo', Array)
#4 /Users/gabi/tmp/proxy/test.php(26): GenericDecorator\DecoratorBuilder->newDecorator in /Users/gabi/tmp/proxy/test.php on line 10
```

**Comment by JeroenDeDauw** [comment]
Presumably gets fixed by reverting https://github.com/JeroenDeDauw/GenericDecorator/commit/ad26fc64404c96822e3858746f5dc211cf42ef6a (though better to find another way. And a test should be added)
